import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div className={styles.effectOne}>
              <Link href="/useEffectOne">UseEffectOne</Link>
          </div>
          <div className={styles.effectTwo}>
              <Link href="/useEffectTwo">UseEffectTwo</Link>          
          </div>
          <div className={styles.effectThree}>
              <Link href="/useEffectThree">UseEffectThree</Link>          
          </div>
          <div className={styles.carousel}>
              <Link href="/carouselPage">Carousel Page</Link>          
          </div>
      </main>
    </>
  )
}
